### ISSUE TITLE
CALIBRATE_Z_PROBE_OFFSET does not run from touchscreen

### ISSUE THREAD

**Issue by shadow2354** [OpenNeptune3D/display_connector#19]
CALIBRATE_Z_PROBE_OFFSET does not run from touchscreen - can only get it to trigger by running macro in the web interface.

**Comment by writepatrick** [comment]
Same here. I completely reflashed and updated everything. 
Still 3 options to chose from:
Screw tilt adjust
Z-probe (which shows the stock screen from elegoo by clicking on it, but without function)
Bed mesh calibrate.
Where the changes made at some point, this is since my last update cycle beginning July.

**Comment by halfmanbear** [comment]
fixed in main
